config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :records

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user

  enum speed: { slow: 100, normal: 140, fast: 180 }

  validates :jump_time, numericality: { only_integer: true }, allow_blank: true
  validates :jump_total_count, numericality: { only_integer: true }, allow_blank: true
  validates :walk_count, numericality: { only_integer: true }, allow_blank: true
  validates :total_distance, presence: true
  validates :recorded_at, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :records
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  validates :password, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  GOAL_DISTANCE = 384_400 # 月の距離（定数のため大文字定義）
  RABBIT_INTERVAL = 10_000 # うさぎが仲間に加わる数字（月の距離 / 10,000）

  def total_distance
    records.sum(:total_distance) # userモデルに定義しているため、ユーザーを指定する必要はない。（current_user.records.total_distanceとする必要がない）
  end

  def remaining_distance # 残りの距離
    [ GOAL_DISTANCE - total_distance, 0 ].max # 配列にして、最大数を返すようにしている。（負の数値が表示されないようにするため。
  end

  def rabbit_count
    (total_distance / RABBIT_INTERVAL).floor
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # /users/sign_up
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name ])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user! # 各アクションが動く前にログインしているかしていないかを判断し、ログインしていなければアクションを動かすことなくログインページが表示されるようする
  before_action :set_record, only: [ :show, :edit, :update ]

  def index
    @records = current_user.records.order(created_at: :desc)

    @totals = {
    jump_time:         @records.sum(:jump_time),
    jump_total_count:  @records.sum(:jump_total_count),
    walk_count:        @records.sum(:walk_count),
    total_distance:    @records.sum(:total_distance)
  }
  end

  def new
    @record = Record.new
  end

  def create
    @record = current_user.records.build(record_params)
    if @record.save
      redirect_to root_path, notice: "記録が保存されました！"
    else
      flash.now[:alert] = "登録に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @record.update(record_params)
      redirect_to records_path, notice: "記録を更新しました！"
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    record = current_user.records.find(params[:id])
    record.destroy!
    redirect_to records_path, notice: "削除しました", status: :see_other
  end

  private

  def record_params
    params.require(:record).permit(:jump_time, :speed, :jump_total_count, :walk_count, :total_distance, :recorded_at)
  end

  def set_record
    @record = current_user.records.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/home/index.html.erb
<div class="w-full min-h-screen flex justify-center items-center">
  <div style="max-width: 600px; text-align: center; padding: 20px;">
    <% if user_signed_in? %>
      <h1>🚀 Let's Go to the Mooooon!!</h1>
      <p>🌕 月まであと <strong> <%= number_with_delimiter(current_user.remaining_distance.floor) %> km</strong>!!</p>
      <p>🐰 現在 <strong> <%= current_user.rabbit_count %> 匹</strong> の仲間がいます</p>
      <div style="margin-top: 20px;">
        <%= link_to '本日の記録を行う！', new_record_path, class: "class: bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md" %>
      </div>
      <div style="margin-top: 20px;">
        <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
      </div>

    <% else %>
      <h1>🚀 Let's Go to the Mooooon!!</h1>
      <p style="margin-top: 20px;">
        このアプリは縄跳びとウォーキングの記録アプリです。<br>
        1万キロ達成ごとにうさぎを仲間に加え月までめざしましょう!!
      </p>
      <p style="margin-top: 20px;">
        ※このアプリを使用するにはログインが必要になります。<br>
        下記からログイン、新規登録をお願い致します。
      </p>
      <div style="margin-top: 10px;">
        <%= link_to 'ログイン', new_user_session_path, style: 'margin-right: 10px;' %>
      </div>
      <div style="margin-top: 1px;">
        <%= link_to '新規登録', new_user_registration_path, style: 'margin-right: 10px;' %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Moon" %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <!-- <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png"> -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet"/>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <!-- flashメッセージを表示できるようにする -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

      <%= render 'shared/header' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/records/_record.html.erb
<%= form_with model: @record, local: true, class: "max-w-xl mx-auto space-y-6", data: { controller: "record-form" } do |f| %>
<%= render 'shared/error_messages', object: f.object %>
  <div>
    <%= f.label :recorded_at, "記録日", class: "block text-sm font-medium text-gray-700" %>
    <%= f.date_field :recorded_at, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 focus:border-blue-500 focus:ring focus:ring-blue-200 focus:ring-opacity-50" %>
  </div>

  <div>
    <%= f.label :jump_time, "縄跳び時間（分）", class: "block text-sm font-medium text-gray-700" %>
    <%= f.number_field :jump_time, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 focus:border-blue-500 focus:ring focus:ring-blue-200 focus:ring-opacity-50", data: { record_form_target: "jumpTime", action: "input->record-form#updateJumpTotal" } %>
  </div>

  <div>
    <%= f.label :speed, "1分間当たりの回数", class: "block text-sm font-medium text-gray-700" %>
    <%= f.select :speed,[ ["100step / 分", "slow"], ["140step / 分", "normal"], ["180step / 分", "fast"] ], { prompt: "選択してください" }, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 focus:border-blue-500 focus:ring focus:ring-blue-200 focus:ring-opacity-50", data: { record_form_target: "speedSelect", action: "change->record-form#updateJumpTotal" } %>
  </div>

  <div>
    <%= f.label :jump_total_count, "累計縄跳び回数", class: "block text-sm font-medium text-gray-700" %>
    <%= f.number_field :jump_total_count, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 focus:border-blue-500 focus:ring focus:ring-blue-200 focus:ring-opacity-50", data: { record_form_target: "jumpTotalCount" } %>
  </div>

  <div>
    <%= f.label :walk_count, "歩数", class: "block text-sm font-medium text-gray-700" %>
    <%= f.number_field :walk_count, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 focus:border-blue-500 focus:ring focus:ring-blue-200 focus:ring-opacity-50", data: { action: "input->record-form#updateDistance", record_form_target: "walkCount" } %>
  </div>

  <div>
    <%= f.label :total_distance, "アプリ内での総移動距離（km）", class: "block text-sm font-medium text-gray-700" %>
    <%= f.number_field :total_distance, step: 1, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm p-2 focus:border-blue-500 focus:ring focus:ring-blue-200 focus:ring-opacity-50", data: { record_form_target: "totalDistance" }, readonly: true %>
  </div>

  <div class="text-center">
    <%= f.submit "保存", class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md" %>
    <%= link_to '一覧へ戻る', records_path, class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md"%>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1 class="text-2xl font-bold mb-6 text-center">記録を変更</h1>
<%= render 'record', record: @record %>

app/views/records/index.html.erb
<h1 class="text-2xl font-bold mb-4">記録一覧</h1>

<%= link_to '新しい記録を作成', new_record_path, class: "bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600" %>

<table class="min-w-full mt-4 border border-gray-300">
  <thead class="bg-gray-100">
    <tr>
      <th class="border px-4 py-2">日付</th>
      <th class="border px-4 py-2">縄跳び時間（分）</th>
      <th class="border px-4 py-2">累計縄跳び回数</th>
      <th class="border px-4 py-2">歩数</th>
      <th class="border px-4 py-2">アプリ内での総移動距離（km）</th>
      <th class="border px-4 py-2"></th>
    </tr>
  </thead>
  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td class="border px-4 py-2 text-center"><%= record.recorded_at %></td>
        <td class="border px-4 py-2 text-center"><%= record.jump_time %></td>
        <td class="border px-4 py-2 text-center"><%= record.jump_total_count %></td>
        <td class="border px-4 py-2 text-center"><%= record.walk_count %></td>
        <td class="border px-4 py-2 text-center"><%= record.total_distance %></td>
        <td class="border px-4 py-2 space-x-2">
          <div class="flex justify-center space-x-2">
            <%= link_to '詳細', record_path(record), class: "bg-blue-500 hover:bg-blue-600 text-white py-1 px-2 rounded-md" %>
            <%= link_to '編集', edit_record_path(record), class: "bg-green-500 hover:bg-green-600 text-white py-1 px-2 rounded-md" %>
          </div>
        </td>
      </tr>
    <% end %>
    <tr style="font-weight: bold;">
      <td class="border px-4 py-2 text-center bg-gray-100">合計</td>
      <td class="border px-4 py-2 text-center bg-gray-100"><%= @totals[:jump_time] %></td>
      <td class="border px-4 py-2 text-center bg-gray-100"><%= @totals[:jump_total_count] %></td>
      <td class="border px-4 py-2 text-center bg-gray-100"><%= @totals[:walk_count] %></td>
      <td class="border px-4 py-2 text-center bg-gray-100"><%= @totals[:total_distance] %></td>
      <td class="border px-4 py-2 text-center bg-gray-100"></td>
    </tr>
  </tbody>
</table>

app/views/records/new.html.erb
<h1 class="text-2xl font-bold mb-6 text-center">新しい記録を追加</h1>
<%= render 'record', record: @record %>

app/views/records/show.html.erb
<h1 class="text-2xl font-bold mb-6 text-center">記録の詳細</h1>

<div class="max-w-xl mx-auto space-y-6">
  <div>
    <label class="block text-sm font-medium text-gray-700">記録日</label>
    <p class="mt-1 block w-full rounded-md border border-gray-300 shadow-sm p-2 bg-gray-100">
      <%= @record.recorded_at %>
    </p>
  </div>

  <div>
    <label class="block text-sm font-medium text-gray-700">縄跳び時間（分）</label>
    <p class="mt-1 block w-full rounded-md border border-gray-300 shadow-sm p-2 bg-gray-100">
      <%= @record.jump_time %>
    </p>
  </div>

  <div>
    <label class="block text-sm font-medium text-gray-700">1分間当たりの回数</label>
    <p class="mt-1 block w-full rounded-md border border-gray-300 shadow-sm p-2 bg-gray-100">
      <%= I18n.t("activerecord.enum.record.speed.#{@record.speed}") %>
    </p>
  </div>

  <div>
    <label class="block text-sm font-medium text-gray-700">累計縄跳び回数</label>
    <p class="mt-1 block w-full rounded-md border border-gray-300 shadow-sm p-2 bg-gray-100">
      <%= @record.jump_total_count %>
    </p>
  </div>

  <div>
    <label class="block text-sm font-medium text-gray-700">歩数</label>
    <p class="mt-1 block w-full rounded-md border border-gray-300 shadow-sm p-2 bg-gray-100">
      <%= @record.walk_count %>
    </p>
  </div>

  <div>
    <label class="block text-sm font-medium text-gray-700">アプリ内での総移動距離（km）</label>
    <p class="mt-1 block w-full rounded-md border border-gray-300 shadow-sm p-2 bg-gray-100">
      <%= @record.total_distance %>
    </p>
  </div>

<div class="text-center space-x-4 flex justify-center">
  <%= link_to "編集", edit_record_path(@record), class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md" %>

  <%= button_to "削除", record_path(@record), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded-md", form: { class: "inline-block" } %>
</div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="flex h-20 items-center justify-between border-b-2 px-4">
    <h1 class="px-3 text-2xl">
      <%= link_to root_path do %>
        <%= image_tag 'favicon.ico', alt: 'ロゴ' %>
      <% end %>
    </h1>
    <% if user_signed_in? %>
    <nav>
      <button
        id="menuBtn"
        type="button"
        class="fixed top-3 right-4 z-10 flex h-14 w-14 items-center justify-center rounded-md border-none bg-purple-950 text-yellow-200 sm:hidden"
      >
        <!-- https://fontawesome.com/icons/bars?s=solid&f=classic -->
        <i id="menuIconBars" class="fa-solid fa-bars fa-2x"></i>

        <!-- https://fontawesome.com/icons/xmark?s=solid&f=classic -->
        <i id="menuIconX" class="fa-solid fa-xmark fa-2x hidden"></i>
      </button>
        <ul
          id="menu"
          class="fixed top-0 left-0 z-0 flex w-full translate-x-full flex-col bg-purple-950 text-center font-bold text-white transition-all ease-linear sm:static sm:w-full sm:translate-x-0 sm:flex-row sm:place-items-center sm:bg-white sm:text-black"
        >
        <li class="p-3">
          <%= link_to 'トップページ', root_path %>
        </li>
        <li class="p-3">
          <%= link_to '記録ページ', new_record_path %>
        </li>
        <li class="p-3">
          <%= link_to '過去の記録一覧', records_path %>
        </li>
        <li class="p-3">
          <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </nav>
    <% end %>
  </div>
</header>

<script>
  menuBtn.addEventListener('click', () => {
  // クリックした時に、"translate-x-full"を追加、削除する。
  // "translate-x-full"が追加されると
  // menuが画面の外に位置するので非表示となる。
    menu.classList.toggle('translate-x-full');
    menuIconBars.classList.toggle('hidden');
    menuIconX.classList.toggle('hidden');
  });
</script>